---
- hosts: admins
  vars_files:
    - vars/secrets.yml
  roles:
    # The guard ensures that this role is executed only once -- cf. http://docs.ansible.com/ansible/playbooks_delegation.html#run-once
    - { role: mysql_users, tags: [ 'mysql_users' ], _mysql_users: "{{ MYSQL_USERS }}", when: "{{ inventory_hostname == groups['admins'][0] }}" }

- hosts: monitors
  become: Yes
  vars_files:
    - vars/secrets.yml
    - group_vars/admins.yml
  roles:
    - { role: grafana, tags: [ 'grafana' ], _grafana: "{{ GRAFANA }}" }

